apiVersion: v1
kind: PersistentVolume
metadata:
    name: my-volume
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: /Users/leaphu/data/my-volume
