apiVersion: v1
kind: PersistentVolume
metadata:
    name: my-volume
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    awsElasticBlockStore:
        volumeId: vol-xxxxxxxx
        fsType: ext4
